#!/bin/bash

check() {
    require_binaries "$WORK_DIR/clmixer" || return 1
    return 255
}

depends() {
    echo "base debug"
    return 0
}

install() {
    # binaries.
    inst "$WORK_DIR/clmixer" "/usr/local/bin/clmixer"

    # intel.
    inst "/etc/OpenCL/vendors/intel64.icd"
    inst "/usr/lib/OpenCL/vendors/intel/*"
    inst "/opt/intel/opencl-1.2-4.4.0.117/lib64/*"
}